/* include/config.h.  Generated by configure.  */
/* include/config.h.in.  Generated from configure.in by autoheader.  */

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `gc' library (-lgc). */
#define HAVE_LIBGC 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Name of package */
#define PACKAGE "scriptix"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "http://www.awemud.net/bugs/submit.php"

/* Define to the full name of this package. */
#define PACKAGE_NAME "Scriptix"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "Scriptix 0.30"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "scriptix"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.30"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Interface version */
#define SX_INTERFACE "0"

/* Software version */
#define SX_VERSION "0.30"

/* Version number of package */
#define VERSION "0.30"
