# Generated automatically from Makefile.in by configure.
all:

clean:

dist-clean:

dist:
	mkdir ../scriptix/deb/
	cp -f dirs deb-update.sh control.in changelog rules README.debian Makefile.in copyright ../scriptix/deb/
